### ISSUE TITLE
项目有找不到的东西

### ISSUE THREAD

**Issue by viewpager** [yexiaochai/Hybrid#2]
你好，作者。刚下载了你的代码，打开后UpdateApp的new BinaryHttpResponseHandler这个找不到，请问怎么回事呢？我只把gradle修改成了我用的版本，代码没有改变。

**Comment by zrx7899** [comment]
BinaryHttpResponseHandler 是android-async-http-1.4.8.jar的一个类。

**Comment by viewpager** [comment]
这个jar在lib_hybrid依赖已经引用了，我没有改你的任何代码。我是用AndroidStudio打开Hybrid-master\andriod这个项目的。

**Comment by viewpager** [comment]
你说的那个jar已经在lib功能引用了，现在导包时间import org.apache.http.Header;这个Header报红。

**Comment by viewpager** [comment]
你说的那个jar已经在lib项目中引用了，现在导包时间import org.apache.http.Header;这个Header报红。我没有改你的任何代码。

**Comment by zrx7899** [comment]
compileSdkVersion 23 改为compileSdkVersion 22 
android 6.0已经移除httpclient

**Comment by viewpager** [comment]
谢谢LZ，可以运行了。不过你那2频道，功能貌似一样啊！
