### ISSUE TITLE
iOS  swift3 时，一堆错误，建议还是写个 oc 的吧 

### ISSUE THREAD

**Issue by loumzy** [yexiaochai/Hybrid#5]

**Comment by suncry** [comment]
很久没更新代码了，项目不那么忙的时候，会把最新代码放上来。但是不会有OC版本

**Comment by loumzy** [comment]
error: The following binaries use incompatible versions of Swift:
/Users/loumzy/Library/Developer/Xcode/DerivedData/Fanli-csgkkxnolmecssaddatxubnygtel/Build/Products/Debug-iphoneos/DogHybrid.framework/DogHybrid

现在木有办法用啊，安卓的还可以正常使用

**Comment by loumzy** [comment]
有没有打包好的 framework 跟新一下，研究研究啊，
